[local]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[all:vars]
ansible_user=root
docker_image=sachindevops1311/jenkins-app:latest
app_port=5000
container_name=jenkins-app